"""
Generates pragma ^0.8.0 interface stubs from graph contract signatures.

Used by TestWriter in bridge mode: when target contracts use pre-0.8 Solidity,
the test file (^0.8.0) cannot import legacy .sol files directly. Instead it
imports this auto-generated BridgeInterfaces.sol and uses deployCode() to
deploy legacy contracts, interacting via ABI-compatible interfaces.
"""

from __future__ import annotations

import re
from typing import Dict, List


BRIDGE_HEADER = """\
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// AUTO-GENERATED by Penteam BridgeInterfaceGenerator
// These are 0.8-compatible interface stubs for legacy contracts.
// Do NOT import legacy .sol files — use these interfaces + deployCode().
"""

_SKIP_NAMES = frozenset({"constructor", "fallback", "receive", "slitherConstructorVariables"})

_UINT_RE = re.compile(r'\buint\b(?!\d)')
_INT_RE = re.compile(r'\bint\b(?!\d)')

_SOLIDITY_PRIMITIVES = frozenset({
    "address", "bool", "string", "bytes",
    "bytes1", "bytes2", "bytes3", "bytes4", "bytes8", "bytes16", "bytes20", "bytes32",
    *(f"uint{n}" for n in range(8, 257, 8)),
    *(f"int{n}" for n in range(8, 257, 8)),
})


_REFERENCE_TYPES = frozenset({"string", "bytes"})


def _sanitize_type(raw: str) -> str:
    """
    Convert a Slither-derived type to a ^0.8.0-safe type for interface stubs.

    Contract/interface/enum/struct types (e.g. ComptrollerInterface, MathError)
    don't exist in the standalone bridge file. Map them to ABI-compatible primitives:
    - contract/interface types -> address
    - array of unknowns -> address[]
    - reference types (string, bytes, arrays) get 'calldata' annotation
    """
    t = raw.strip()
    t = _UINT_RE.sub("uint256", t)
    t = _INT_RE.sub("int256", t)

    t = t.replace(" memory", "").replace(" calldata", "").replace(" storage", "")

    is_array = t.endswith("[]")
    base = t[:-2].strip() if is_array else t

    if base in _SOLIDITY_PRIMITIVES:
        if is_array:
            return f"{base}[] calldata"
        if base in _REFERENCE_TYPES:
            return f"{base} calldata"
        return base

    if is_array:
        return "address[] calldata"
    return "address"


def _parse_signature(sig: str) -> tuple[str, list[str]] | None:
    """
    Parse 'funcName(type1,type2)' into ('funcName', ['type1', 'type2']).
    Returns None if unparseable.
    """
    m = re.match(r'^(\w+)\(([^)]*)\)$', sig.strip())
    if not m:
        return None
    name = m.group(1)
    params_str = m.group(2).strip()
    if not params_str:
        return name, []
    params = [p.strip() for p in params_str.split(",")]
    return name, params


def generate_bridge_interfaces(
    contract_names: list[str],
    all_signatures: Dict[str, Dict[str, str]],
    graph=None,
) -> str:
    """
    Generate a single BridgeInterfaces.sol file with interface stubs.

    Args:
        contract_names: list of contract names to generate interfaces for.
        all_signatures: {contract_name: {fn_name: signature_str}}
        graph: optional networkx graph (used to look up visibility/mutability).

    Returns:
        The complete Solidity source as a string.
    """
    blocks: list[str] = []

    for contract_name in contract_names:
        sigs = all_signatures.get(contract_name, {})
        if not sigs:
            continue
        lines = _build_interface(contract_name, sigs, graph)
        if lines:
            blocks.append(lines)

    if not blocks:
        return BRIDGE_HEADER + "\n// No interfaces generated (no public signatures found).\n"

    return BRIDGE_HEADER + "\n\n" + "\n\n".join(blocks) + "\n"


def _build_interface(
    contract_name: str,
    sigs: Dict[str, str],
    graph=None,
) -> str:
    """Build a single interface block for one contract."""
    fn_lines: list[str] = []

    for fn_name, raw_sig in sorted(sigs.items()):
        if fn_name in _SKIP_NAMES or fn_name.startswith("_"):
            continue

        parsed = _parse_signature(raw_sig)
        if not parsed:
            continue

        _, param_types = parsed

        visibility = "external"
        mutability = ""
        returns_clause = ""
        is_payable = False

        if graph is not None:
            node_id = f"{contract_name}::{fn_name}"
            node_data = graph.nodes.get(node_id, {})
            if node_data.get("visibility") in ("internal", "private"):
                continue
            if node_data.get("is_view_or_pure"):
                pure = node_data.get("is_pure", False)
                mutability = " pure" if pure else " view"
            # Check if function is payable from graph data
            is_payable = bool(node_data.get("is_payable", False))
        else:
            # No graph: for pre-0.8 contracts, non-view functions default to payable
            # because Solidity 0.4/0.5 functions were payable by default
            is_payable = True

        # If graph exists but doesn't have is_payable field, fall back to
        # assuming payable for any non-view/non-pure function in a legacy contract
        if graph is not None and not mutability and not is_payable:
            node_id = f"{contract_name}::{fn_name}"
            node_data = graph.nodes.get(node_id, {})
            # If there's no explicit is_payable=False set, assume payable for safety
            # Legacy 0.4.x contracts had payable as default behavior
            if "is_payable" not in node_data:
                is_payable = True

        params_str = ", ".join(
            f"{_sanitize_type(t)} arg{i}" for i, t in enumerate(param_types)
        )

        # Build the function line with payable if needed
        payable_kw = " payable" if (is_payable and not mutability) else ""
        fn_line = f"    function {fn_name}({params_str}) external{payable_kw}{mutability}{returns_clause};"
        fn_lines.append(fn_line)

    if not fn_lines:
        return ""

    header = f"interface I{contract_name} {{"
    footer = "}"
    return header + "\n" + "\n".join(fn_lines) + "\n" + footer


def resolve_deploy_code_path(contract_name: str, repo_manifest: list[str], real_sources: dict[str, str] | None = None) -> str:
    """
    Resolve the correct artifact path for Foundry's deployCode() cheatcode.

    deployCode() takes "path/to/File.sol:ContractName" style paths.
    Search repo_manifest for .sol files likely containing the contract.
    """
    exact_matches = [
        f for f in repo_manifest
        if f.endswith(f"/{contract_name}.sol") or f == f"{contract_name}.sol"
    ]
    if exact_matches:
        return f"{sorted(exact_matches, key=len)[0]}:{contract_name}"

    fuzzy_matches = [
        f for f in repo_manifest
        if f.endswith(".sol") and contract_name.lower() in f.lower()
    ]
    if fuzzy_matches:
        return f"{sorted(fuzzy_matches, key=len)[0]}:{contract_name}"

    if real_sources:
        import re
        pattern = re.compile(rf'\b(?:contract|library|interface)\s+{contract_name}\b')
        for path, code in real_sources.items():
            if pattern.search(code):
                return f"{path}:{contract_name}"

    return f"contracts/{contract_name}.sol:{contract_name}"
